[tool.kedro]
package_name = "template_project"
project_name = "template_project"
kedro_init_version = "0.19.1"

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = """
--cov-report term-missing \
--cov src/template_project -ra"""

[tool.coverage.report]
fail_under = 0
show_missing = true
exclude_lines = ["pragma: no cover", "raise NotImplementedError"]

[tool.black]
include = '\.pyi?$'
